from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

#Chatbot class (configurations of chatterbot AI library)
class AI_engine:
    def __init__(self, user_input_en="") -> str:
        self.chatbot = ChatBot("Sad bot engine")
        self.user_input_en = user_input_en
        self.trainer = ChatterBotCorpusTrainer(self.chatbot)
        
        # Here response is generated by the ChatterBot engine, after user input.
    def sad_bot_ai(self) -> str:
        response = self.chatbot.get_response(self.user_input_en)
        return response

        # Function initiates learning of english conversations
    def learn_english(self, parameter: str) -> None:
        self.trainer.train(f'chatterbot.corpus.english.{parameter}')
        
        # Conversation and Chatbot memory wipe
    def bot_memory_wipe(self) -> None:
        self.chatbot.storage.drop()



        
        